"""all done 

Revision ID: 02eb5419c039
Revises: 2e205dccc7fd
Create Date: 2025-09-03 08:38:32.095730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02eb5419c039'
down_revision = '2e205dccc7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('from_meter', sa.Float(), nullable=True),
    sa.Column('to_meter', sa.Float(), nullable=True),
    sa.Column('serial_no', sa.String(length=50), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('return_product')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    op.create_table('return_product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('from_meter', mysql.FLOAT(), nullable=True),
    sa.Column('to_meter', mysql.FLOAT(), nullable=True),
    sa.Column('serial_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('returned_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('return_product_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('return_product_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('return')
    # ### end Alembic commands ###
